### PR TITLE
Upgrade to FSharp.Core 7+ and newer FSharp.CompilerServices

### PR DESCRIPTION
**Pull request by DamianReeves**
This fixes issues where even the Options example in this repo doesn't work if you are using dotnet7

### CODE REVIEW

**Comment by bigjonroberts** [comment]
Nice

**Comment by bigjonroberts** [comment]
I just tried this out on Windows 10 with dotnet sdk version 7.0.101 and had a similar error as #66 .
I'll try it out under debug later this weekend and see if I can get the detailed error message.
The Analyzers need to output more detailed error messages to allow easier diagnosis of issues like this.  I might put in a PR for that ...

image

**Comment by DamianReeves** [comment]
> I just tried this out on Windows 10 with dotnet sdk version 7.0.101 and had a similar error as #66 . I'll try it out under debug later this weekend and see if I can get the detailed error message. The Analyzers need to output more detailed error messages to allow easier diagnosis of issues like this. I might put in a PR for that ...
> 
> image

I think I had to do a `-c Release` when I ran.

**Comment by baronfel** [comment]
Sorry for the delay here - thanks for tackling this @DamianReeves!

**Pull request merged**
