### PR TITLE
New dotnet.proj info

### PR DESCRIPTION
**Pull request by tforkmann**
Hi there,

I implemented to new `Ionide.ProjInfo` package.
It is compiling for now. But I'm not sure if the glob filter is required in the `runProject` function.

Could you please have a look over the PR?

Thanks,

Tim

### CODE REVIEW

**Comment by baronfel** [comment]
@tforkmann I sent an MR to your fork with a couple tweaks to this, if you can review them at your leisure.

**Comment by tforkmann** [comment]
@baronfel @Krzysztof-Cieslak Can this be merged?

**Comment by baronfel** [comment]
Yeah, thanks for taking the time to do this!

**Comment by tforkmann** [comment]
Thanks to you for helping out! Could you please release the new changes? I want to try if the updates works with my Analyzer.

**Comment by baronfel** [comment]
[0.6.0](https://www.nuget.org/packages/FSharp.Analyzers.SDK/0.6.0) is indexing on Nuget now, enjoy!

**Pull request merged**
